# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "release" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: uni test
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test -- --watch=false --browsers=ChromeHeadless
  CI:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: uni test
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run build
          tar -zcvf release.tgz ./dist
      - name: Read JSON
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: alpha-v${{ steps.version.outputs.value }}
          release_name: Release rc-${{ steps.version.outputs.value }}
          draft: false # 是否是草稿
          prerelease: false # 是否是预发布

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tgz
          asset_name: release.tgz
          asset_content_type: application/x-tgz

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Read JSON
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: '45.77.25.170'
          username: 'root'
          password: 'a(W9#4#cv.k_D}D{'
          port: '22'
          script: |
            cd /www/wwwroot/www.suag.top
            rm -rf ./release.tgz
            wget https://github.com/su4g/ng-action/releases/download/alpha-v${{ steps.version.outputs.value }}/release.tgz
            zxvf release.tgz

        
